repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: ['--py38-plus']

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.289'
    hooks:
      - id: ruff
        args:
          - --fix

