repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: ['--py39-plus']

repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  -  repo: https://github.com/pre-commit/pre-commit-hooks
     rev: v1.2.3
     hooks:
        - id: flake8


