site_name: Poi Docs
nav:
    - Introduction: index.md
    - Basic Usage: basic-usage.md
    - Advanced Features: advanced.md

theme: material


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences